# Generated by Django 4.1.7 on 2023-12-09 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='annee_formation',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AddField(
            model_name='groupe',
            name='biographie',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='groupe',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock')], default='HH', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupe',
            name='page_officielle',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
