# Generated by Django 4.1.7 on 2023-12-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_groupe_actif_groupe_annee_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='annee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupe',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
