# Generated by Django 4.1.7 on 2023-12-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Articles',
        ),
    ]
