# Generated by Django 4.1.7 on 2023-12-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_listings_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
