# Generated by Django 4.1.7 on 2023-12-09 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_articles_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.groupe'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='annee_formation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='biographie',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='page_officielle',
            field=models.URLField(blank=True, null=True),
        ),
    ]
